I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1041, in script
    $ cas_affection -=2
  File "game/script.rpy", line 1041, in <module>
    $ cas_affection -=2
NameError: name 'cas_affection' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1041, in script
    $ cas_affection -=2
  File "renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1041, in <module>
    $ cas_affection -=2
NameError: name 'cas_affection' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 7.6.3.23091805
Crimson Nights 1.0
Mon Oct 30 21:40:30 2023
