I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cass route.rpy", line 420, in script
    $ petname == "Red"
  File "game/cass route.rpy", line 420, in <module>
    $ petname == "Red"
NameError: name 'petname' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/cass route.rpy", line 420, in script
    $ petname == "Red"
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/cass route.rpy", line 420, in <module>
    $ petname == "Red"
NameError: name 'petname' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 7.6.1.23060707
Crimson Nights 1.0
Tue Oct 10 20:41:29 2023
