I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cass route.rpy", line 1564, in script
    "You smile. With the Vellsings and the Batbashers dealt with, [townname] has become a new safe haven for the vampire community."
KeyError: u'townname'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/cass route.rpy", line 1564, in script
    "You smile. With the Vellsings and the Batbashers dealt with, [townname] has become a new safe haven for the vampire community."
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/exports.py", line 1473, in say
    who(what, *args, **kwargs)
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'townname'

Windows-10-10.0.22621 AMD64
Ren'Py 7.6.1.23060707
Crimson Nights 1.0
Wed Oct 11 17:47:29 2023
